version: '3.3'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - 5432:5432
    expose:
      - 5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    networks:
      - memcode_network
  memcode:
    build:
      context: ./memcode
      dockerfile: ./Dockerfile
    working_dir: /usr/src/app
    volumes:
      - ./memcode/:/usr/src/app/
    links:
      - db
    ports:
      - 5001:3000
    networks:
      - memcode_network
    depends_on:
      - db
networks:
    memcode_network: